hmpps.sqs:
  provider: localstack
  queues:
    audit:
      queueName: ${random.uuid}
    incidentreporting:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: domainevents
      subscribeFilter: >-
        {"eventType": [
          "prison-offender-events.prisoner.merged",
          "prison-offender-events.prisoner.booking.moved"
        ]}
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
