server:
  shutdown: immediate

api:
  base:
    url:
      oauth: http://localhost:8090/auth
      prisoner-search: http://localhost:8081
      manage:
        users: http://localhost:8082

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  devtools:
    add-properties: true

  datasource:
    url: jdbc:postgresql://localhost:5432/incident_reporting?sslmode=prefer
    username: incident_reporting
    password: incident_reporting
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: false
