server:
  shutdown: immediate

api:
  base:
    url:
      oauth: http://localhost:9090/auth

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  devtools:
    add-properties: true
