apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-incident-reporting-api-refresh-views
spec:
  {{- if (eq .Values.environment.name "prod") }}
  schedule: "00 03 * * *"
  {{- else }}
  schedule: "00 20 * * 1-5"
  {{- end }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: refresh-views
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPUT http://hmpps-incident-reporting-api/refresh-views
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
