---
generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: incident-reporting-api-dev.hmpps.service.justice.gov.uk

  allowlist: null

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
