generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true
    startup: '49 6 * * 1-5' # Start at 6.49am UTC Monday-Friday
    shutdown: '58 21 * * 1-5' # Stop at 9.58pm UTC Monday-Friday

  ingress:
    host: incident-reporting-api-dev.hmpps.service.justice.gov.uk

  allowlist: null

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    # temporarily reduce sampling for NOMIS migration in dev:
    APPLICATIONINSIGHTS_SAMPLING_PERCENTAGE: '1'
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

generic-prometheus-alerts:
  alertSeverity: hmpps-incident-reporting-dev
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-357b6fd216e4b0ae: incident-reporting-api
  sqsAlertsQueueNames:
    - hmpps-incident-reporting-development-prisoner-event-queue
    - hmpps-incident-reporting-development-prisoner-event-dlq
