environment:
  name: dev

generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: incident-reporting-api-dev.hmpps.service.justice.gov.uk

  allowlist: null

  env:
    SPRING_PROFILES_ACTIVE: "logstash, replica"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search-dev.prison.service.justice.gov.uk
    API_BASE_URL_MANAGE_USERS: https://manage-users-api-dev.hmpps.service.justice.gov.uk
    URL_ENV_SUFFIX: dev

  namespace_secrets:
    dps-rds-read-replica-output:
      REPLICA_DATABASE_ENDPOINT: "rds_instance_endpoint"

generic-prometheus-alerts:
  alertSeverity: hmpps-incident-reporting-dev
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-357b6fd216e4b0ae: incident-reporting-api
  sqsAlertsQueueNames:
    - hmpps-incident-reporting-development-prisoner-event-queue
    - hmpps-incident-reporting-development-prisoner-event-dlq
