environment:
  name: preprod

generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: incident-reporting-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search-preprod.prison.service.justice.gov.uk
    API_BASE_URL_MANAGE_USERS: https://manage-users-api-preprod.hmpps.service.justice.gov.uk
    URL_ENV_SUFFIX: preprod

generic-prometheus-alerts:
  alertSeverity: hmpps-incident-reporting-preprod
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-aeef80d0d303f28e: incident-reporting-api
  sqsAlertsQueueNames:
    - hmpps-incident-reporting-preprod-prisoner-event-queue
    - hmpps-incident-reporting-preprod-prisoner-event-dlq
