---
generic-service:
  replicaCount: 2

  ingress:
    host: incident-reporting-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
