environment:
  name: prod

generic-service:
  ingress:
    host: incident-reporting-api.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: false

  resources:
    requests:
      memory: 4G
    limits:
      memory: 6G

  env:
    JAVA_OPTS: "-Xmx3g"
    SPRING_PROFILES_ACTIVE: "logstash, replica"
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search.prison.service.justice.gov.uk
    API_BASE_URL_MANAGE_USERS: https://manage-users-api.hmpps.service.justice.gov.uk

  namespace_secrets:
    dps-rds-read-replica-output:
      REPLICA_DATABASE_ENDPOINT: "rds_instance_endpoint"

  postgresDatabaseRestore:
    enabled: true
    env:
      SCHEMA_TO_RESTORE: "public"
    namespace_secrets:
      dps-rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      dps-rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

generic-prometheus-alerts:
  alertSeverity: hmpps-incident-reporting-prod
  rdsAlertsDatabases:
    cloud-platform-6da4d16fce197ed0: incident-reporting-api
  sqsAlertsQueueNames:
    - hmpps-incident-reporting-production-prisoner-event-queue
    - hmpps-incident-reporting-production-prisoner-event-dlq
