generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true
    startup: '49 6 * * 1-5' # Start at 6.49am UTC Monday-Friday
    shutdown: '58 21 * * 1-5' # Stop at 9.58pm UTC Monday-Friday

  ingress:
    host: incident-reporting-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search-preprod.prison.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: hmpps-incident-reporting-preprod
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-aeef80d0d303f28e: incident-reporting-api
  sqsAlertsQueueNames:
    - hmpps-incident-reporting-preprod-prisoner-event-queue
    - hmpps-incident-reporting-preprod-prisoner-event-dlq
