-- Example values and subject access request (SAR) classification for every column (IR-2037).
--
-- These feed the SAR Data Requirements extract (scripts/generate-sar-data-requirements.sh), the document the
-- Offender SAR team review at the data review checkpoint of the SAR change control process. Incident reporting
-- is going through that process as a New Product (IR-1461), so every element needs an example value and a
-- statement of whether it reaches a prisoner's report. Comments only - no schema or data change.
--
-- Each column comment gains two tags, between the description and the existing sensitivity tag:
--
--   '... description text. [Example: SELF_HARM_1] [SAR: Y] [Sensitivity: SPECIAL-CATEGORY]'
--
-- [SAR: Y] means the value reaches the report under the response proposed for the data review (IR-1424),
-- whether it is rendered from this column or from the column it mirrors. [SAR: N] is for internal keys and
-- display order, NOMIS-only and sync fields, process flags, and the constant_* and analytical_marker reference
-- tables, which the service never reads. The response does not exist yet in that form, so these are a proposal
-- for the Offender SAR team to confirm or change; their decision goes in a later migration rather than an edit
-- to this one.
--
-- The proposal includes other people named on a report - other prisoners and staff - and the free-text fields
-- that routinely describe them. Redacting third-party data is the Offender SAR team's job, so the default is to
-- return it and let them redact. That default is one of the questions put to them at the data review.
--
-- Example values for code columns are real codes. Every other example is invented, and the free-text examples
-- are deliberately bland: they illustrate the kind of content, not real incidents.
--
-- First, five comments from V1_48 are corrected, because the extract quotes them to the Offender SAR team:
--
--   * report.type, history.type and constant_type.code gave SELF_HARM, ASSAULT and FIND_OF_ILLICIT_ITEMS as
--     examples. SELF_HARM and ASSAULT are type family codes, and FIND_OF_ILLICIT_ITEMS does not exist - the
--     type codes carry a numeric suffix (SELF_HARM_1, ASSAULT_5, FIND_6).
--   * prisoner_involvement.prisoner_role gave SUSPECTED_PERPETRATOR, which does not exist - the role is
--     SUSPECTED_ASSAILANT.
--   * report.title said it is written by the reporter. For reports created in DPS it is generated by the
--     UI from the incident type, the prisoners involved and the prison (see the commit that made it TEXT,
--     #534), so it names every prisoner on the report.

COMMENT ON COLUMN report.title IS 'Short title for the incident. For reports created in DPS it is generated automatically from the incident type, the prison number and surname of every prisoner involved and the prison, so it names everyone on the report. Reports that came from NOMIS carry the title the reporter wrote, which in practice often names people or summarises what happened. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN report.type IS 'What kind of incident this is, for example SELF_HARM_1, DEATH_OTHER_1, ASSAULT_5 or FIND_6. Drives which questions are asked. This is Article 9 or Article 10 data about everyone named on the report whichever value it holds - that a report exists and is a self-harm report discloses health data about the prisoner it concerns. Values are listed in constant_type and grouped by constant_type_family. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN prisoner_involvement.prisoner_role IS 'How the prisoner was involved, for example VICTIM, SUSPECTED_ASSAILANT, ACTIVE_INVOLVEMENT or PRESENT_AT_SCENE. On an assault or a find of illicit items, recording someone as a suspected assailant is an allegation of offending in custody against a named person - criminal offence data under Article 10, which DPA 2018 s.11(2) extends to alleged offences. Values are in constant_prisoner_role. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN history.type IS 'The incident type the report held before it was changed - so a report now typed ASSAULT_5 may have a history row typed SELF_HARM_1. Carries the same sensitivity as report.type, and note that it discloses what the incident was once believed to be. Values are in constant_type. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN constant_type.code IS 'The type code as stored in report.type and history.type, for example SELF_HARM_1 or ASSAULT_5. [Sensitivity: NONE]';

DO $$
DECLARE
  rec      record;
  existing text;
BEGIN
  FOR rec IN
    SELECT * FROM (VALUES
      -- The report itself. What happened, where, when and who reported it reaches the report; internal keys,
      -- sync bookkeeping and process flags do not.
      ('report', 'id', '0192a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b', 'N'),
      ('report', 'report_reference', '1234567', 'Y'),
      ('report', 'title', 'Self-harm: A1234BC Smith (MDI)', 'Y'),
      ('report', 'description', 'Officer found the prisoner in their cell with a cut to the forearm. Healthcare attended.', 'Y'),
      ('report', 'location', 'MDI', 'Y'),
      ('report', 'type', 'SELF_HARM_1', 'Y'),
      ('report', 'source', 'DPS', 'N'),
      ('report', 'status', 'AWAITING_REVIEW', 'Y'),
      ('report', 'incident_date_and_time', '2026-03-14T09:30:00', 'Y'),
      ('report', 'reported_at', '2026-03-14T11:05:00', 'Y'),
      ('report', 'reported_by', 'AUSER_GEN', 'Y'),
      ('report', 'question_set_id', 'Never set', 'N'),
      ('report', 'created_at', '2026-03-14T11:05:12', 'N'),
      ('report', 'modified_by', 'AUSER_GEN', 'N'),
      ('report', 'modified_at', '2026-03-15T08:40:00', 'N'),
      ('report', 'modified_in', 'DPS', 'N'),
      ('report', 'staff_involvement_done', 'true', 'N'),
      ('report', 'prisoner_involvement_done', 'true', 'N'),
      ('report', 'duplicated_report_id', '0192a3b4-0000-7e8f-9a0b-1c2d3e4f5a6b', 'N'),
      ('report', 'last_user_action', 'REQUEST_REVIEW', 'Y'),

      -- Prisoners named on the report, including prisoners other than the subject.
      ('prisoner_involvement', 'id', '101', 'N'),
      ('prisoner_involvement', 'report_id', '0192a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b', 'N'),
      ('prisoner_involvement', 'prisoner_number', 'A1234BC', 'Y'),
      ('prisoner_involvement', 'prisoner_role', 'VICTIM', 'Y'),
      ('prisoner_involvement', 'outcome', 'SEEN_HEALTHCARE', 'Y'),
      ('prisoner_involvement', 'comment', 'Minor injury to the hand, seen by healthcare.', 'Y'),
      ('prisoner_involvement', 'sequence', '0', 'N'),
      ('prisoner_involvement', 'first_name', 'John', 'Y'),
      ('prisoner_involvement', 'last_name', 'Smith', 'Y'),

      -- Staff named on the report.
      ('staff_involvement', 'id', '201', 'N'),
      ('staff_involvement', 'report_id', '0192a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b', 'N'),
      ('staff_involvement', 'staff_username', 'BSTAFF_GEN', 'Y'),
      ('staff_involvement', 'staff_role', 'FIRST_ON_SCENE', 'Y'),
      ('staff_involvement', 'comment', 'First to arrive and called for healthcare.', 'Y'),
      ('staff_involvement', 'sequence', '0', 'N'),
      ('staff_involvement', 'first_name', 'Jane', 'Y'),
      ('staff_involvement', 'last_name', 'Doe', 'Y'),

      -- Text added after the report was submitted.
      ('description_addendum', 'id', '301', 'N'),
      ('description_addendum', 'report_id', '0192a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b', 'N'),
      ('description_addendum', 'sequence', '0', 'N'),
      ('description_addendum', 'text', 'Prisoner later said the injury happened in a fall.', 'Y'),
      ('description_addendum', 'created_at', '2026-03-16T10:00:00', 'Y'),
      ('description_addendum', 'created_by', 'AUSER_GEN', 'Y'),
      ('description_addendum', 'first_name', 'Alex', 'Y'),
      ('description_addendum', 'last_name', 'Brown', 'Y'),

      -- The trail of requests and actions on the report.
      ('correction_request', 'id', '401', 'N'),
      ('correction_request', 'report_id', '0192a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b', 'N'),
      ('correction_request', 'description_of_change', 'Please add the names of the staff who attended.', 'Y'),
      ('correction_request', 'correction_requested_at', '2026-03-15T14:20:00', 'Y'),
      ('correction_request', 'correction_requested_by', 'CWARDEN_GEN', 'Y'),
      ('correction_request', 'sequence', '0', 'N'),
      ('correction_request', 'location', 'MDI', 'Y'),
      ('correction_request', 'user_action', 'REQUEST_CORRECTION', 'Y'),
      ('correction_request', 'original_report_reference', '7654321', 'Y'),
      ('correction_request', 'user_type', 'DATA_WARDEN', 'Y'),

      -- The two audit trails: status changes and type changes.
      ('status_history', 'id', '501', 'N'),
      ('status_history', 'report_id', '0192a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b', 'N'),
      ('status_history', 'status', 'NEEDS_UPDATING', 'Y'),
      ('status_history', 'changed_at', '2026-03-15T14:20:00', 'Y'),
      ('status_history', 'changed_by', 'CWARDEN_GEN', 'Y'),

      ('history', 'id', '601', 'N'),
      ('history', 'report_id', '0192a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b', 'N'),
      ('history', 'type', 'ASSAULT_5', 'Y'),
      ('history', 'changed_at', '2026-03-15T09:00:00', 'Y'),
      ('history', 'changed_by', 'AUSER_GEN', 'Y'),

      -- Questions and answers. The question wording is needed to make sense of the answer, so it is disclosed
      -- with it; the stable codes are for analysis and are not.
      ('question', 'id', '701', 'N'),
      ('question', 'report_id', '0192a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b', 'N'),
      ('question', 'sequence', '0', 'N'),
      ('question', 'code', '2001', 'N'),
      ('question', 'question', 'WAS MEDICAL TREATMENT REQUIRED', 'Y'),
      ('question', 'additional_information', 'Treatment refused at first, accepted later.', 'Y'),
      ('question', 'label', 'Was medical treatment required?', 'Y'),

      ('response', 'id', '801', 'N'),
      ('response', 'question_id', '701', 'N'),
      ('response', 'sequence', '0', 'N'),
      ('response', 'response', 'YES', 'Y'),
      ('response', 'response_date', '2026-03-14', 'Y'),
      ('response', 'additional_information', 'Cut cleaned and dressed.', 'Y'),
      ('response', 'recorded_at', '2026-03-14T11:05:00', 'Y'),
      ('response', 'recorded_by', 'AUSER_GEN', 'Y'),
      ('response', 'code', '2001-1', 'N'),
      ('response', 'label', 'Yes', 'Y'),

      -- The question set as it stood before a type change. Disclosed like the current one.
      ('historical_question', 'id', '901', 'N'),
      ('historical_question', 'history_id', '601', 'N'),
      ('historical_question', 'sequence', '0', 'N'),
      ('historical_question', 'code', '2001', 'N'),
      ('historical_question', 'question', 'WAS MEDICAL TREATMENT REQUIRED', 'Y'),
      ('historical_question', 'additional_information', 'Treatment refused at first, accepted later.', 'Y'),
      ('historical_question', 'label', 'Was medical treatment required?', 'Y'),

      ('historical_response', 'id', '1001', 'N'),
      ('historical_response', 'historical_question_id', '901', 'N'),
      ('historical_response', 'sequence', '0', 'N'),
      ('historical_response', 'response', 'YES', 'Y'),
      ('historical_response', 'response_date', '2026-03-14', 'Y'),
      ('historical_response', 'additional_information', 'Cut cleaned and dressed.', 'Y'),
      ('historical_response', 'recorded_at', '2026-03-14T11:05:00', 'Y'),
      ('historical_response', 'recorded_by', 'AUSER_GEN', 'Y'),
      ('historical_response', 'code', '2001-1', 'N'),
      ('historical_response', 'label', 'Yes', 'Y'),

      -- Reference data. About the service's vocabulary, not about anyone, and never read by the service.
      ('analytical_marker', 'response_code', '2001-1', 'N'),
      ('analytical_marker', 'marker_type', 'MEDICAL_TREATMENT_REQUIRED', 'N'),

      ('constant_type', 'code', 'SELF_HARM_1', 'N'),
      ('constant_type', 'sequence', '1', 'N'),
      ('constant_type', 'description', 'Self-harm', 'N'),
      ('constant_type', 'active', 'true', 'N'),
      ('constant_type', 'family_code', 'SELF_HARM', 'N'),

      ('constant_type_family', 'code', 'SELF_HARM', 'N'),
      ('constant_type_family', 'sequence', '1', 'N'),
      ('constant_type_family', 'description', 'Self-harm', 'N'),

      ('constant_status', 'code', 'AWAITING_REVIEW', 'N'),
      ('constant_status', 'sequence', '1', 'N'),
      ('constant_status', 'description', 'Awaiting review', 'N'),
      ('constant_status', 'ignore_downstream', 'false', 'N'),
      ('constant_status', 'definition', 'A report that has been submitted for the first time and is now ready for review.', 'N'),

      ('constant_prisoner_role', 'code', 'VICTIM', 'N'),
      ('constant_prisoner_role', 'sequence', '1', 'N'),
      ('constant_prisoner_role', 'description', 'Victim', 'N'),

      ('constant_prisoner_outcome', 'code', 'SEEN_HEALTHCARE', 'N'),
      ('constant_prisoner_outcome', 'sequence', '1', 'N'),
      ('constant_prisoner_outcome', 'description', 'Seen by Healthcare', 'N'),

      ('constant_staff_role', 'code', 'FIRST_ON_SCENE', 'N'),
      ('constant_staff_role', 'sequence', '1', 'N'),
      ('constant_staff_role', 'description', 'First on scene', 'N'),

      ('constant_user_action', 'code', 'REQUEST_CORRECTION', 'N'),
      ('constant_user_action', 'sequence', '1', 'N'),
      ('constant_user_action', 'description', 'Request correction', 'N'),

      ('constant_user_type', 'code', 'DATA_WARDEN', 'N'),
      ('constant_user_type', 'sequence', '1', 'N'),
      ('constant_user_type', 'description', 'Data warden', 'N')
    ) AS t(table_name, column_name, example, sar_impact)
  LOOP
    SELECT col_description(a.attrelid, a.attnum)
      INTO existing
      FROM pg_attribute a
     WHERE a.attrelid = format('%I', rec.table_name)::regclass
       AND a.attname = rec.column_name
       AND a.attnum > 0
       AND NOT a.attisdropped;

    IF existing IS NULL THEN
      RAISE EXCEPTION 'No comment on %.% - describe the column before classifying it',
        rec.table_name, rec.column_name;
    END IF;

    IF position(' [Sensitivity:' IN existing) = 0 THEN
      RAISE EXCEPTION 'Comment on %.% has no sensitivity tag to place the new tags before',
        rec.table_name, rec.column_name;
    END IF;

    IF position('[Example:' IN existing) > 0 OR position('[SAR:' IN existing) > 0 THEN
      RAISE EXCEPTION 'Comment on %.% is already tagged', rec.table_name, rec.column_name;
    END IF;

    IF position(']' IN rec.example) > 0 THEN
      RAISE EXCEPTION 'Example for %.% contains "]", which would end the tag early',
        rec.table_name, rec.column_name;
    END IF;

    EXECUTE format(
      'COMMENT ON COLUMN %I.%I IS %L',
      rec.table_name,
      rec.column_name,
      replace(
        existing,
        ' [Sensitivity:',
        ' [Example: ' || rec.example || '] [SAR: ' || rec.sar_impact || '] [Sensitivity:'
      )
    );
  END LOOP;
END $$;
